<?php
/**
 * ACF Field Configuration for Pricing Page Template
 *
 * @package SelfScan
 */

if ( function_exists( 'acf_add_local_field_group' ) ) {
    acf_add_local_field_group( array(
        'key' => 'group_pricing_page_content',
        'title' => 'Pricing Page Content',
        'fields' => array(
            // Hero Section
            array(
                'key' => 'field_price_1a2b3c4d5e6f',
                'label' => 'Hero Section',
                'name' => 'pricing_hero_section',
                'type' => 'accordion',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_price_2b3c4d5e6f7g',
                'label' => 'Hero Title',
                'name' => 'pricing_hero_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Transparent Pricing for Your Canadian Background Check',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_price_3c4d5e6f7g8h',
                'label' => 'Price',
                'name' => 'pricing_price',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '$59.99',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_price_4d5e6f7g8h9i',
                'label' => 'Subtitle',
                'name' => 'pricing_subtitle',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Get fast, secure, and accurate criminal background checks from a trusted Canadian provider. Our service searches adult convictions listed in the Canadian Police Information Centre (CPIC) and other national police databases.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_price_5e6f7g8h9i0j',
                'label' => 'Hero Button',
                'name' => 'pricing_button',
                'type' => 'link',
                'instructions' => 'Enter the URL and text for the hero button',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'default_value' => array(
                    'title' => 'Get Started',
                    'url' => '#',
                ),
            ),
            
            // Details Section
            array(
                'key' => 'field_price_3m4n5o6p7q8r',
                'label' => 'Details Section',
                'name' => 'pricing_details_section',
                'type' => 'accordion',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_price_4n5o6p7q8r9s',
                'label' => 'Details Title',
                'name' => 'pricing_details_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'What\'s Included',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_price_5o6p7q8r9s0t',
                'label' => 'Details Text',
                'name' => 'pricing_details_text',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '<p>For one flat fee, you\'ll receive a detailed report based on your name and date of birth, referencing police databases to determine whether a criminal record exists. This is an official name-based check used across Canada for employment, volunteer work, and more.</p>',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            
            // CTA Section
            array(
                'key' => 'field_price_6p7q8r9s0t1u',
                'label' => 'CTA Section',
                'name' => 'pricing_cta_section',
                'type' => 'accordion',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_price_7q8r9s0t1u2v',
                'label' => 'CTA Title',
                'name' => 'pricing_cta_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Get Started Today',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_price_8r9s0t1u2v3w',
                'label' => 'CTA Subtitle',
                'name' => 'pricing_cta_subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Skip the lines and get your official Canadian background check completed online—usually in minutes.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_price_9s0t1u2v3w4x',
                'label' => 'CTA Button',
                'name' => 'pricing_cta_button',
                'type' => 'link',
                'instructions' => 'Enter the URL and text for the CTA button',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'default_value' => array(
                    'title' => 'Start Background Check',
                    'url' => '#',
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/template-pricing.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ) );
} 